---
title: "maximizing cross-correlation"
output: pdf_document
---

Consider $X=(X_1,\dots,X_n)^\top$, $Y=(Y_1,\dots,Y_n)^\top$ such that $\mathbb E X_i=\mathbb EY_i=0$ and $\mathbb EX_i^2=\sigma_X^2$, $\mathbb E Y_i^2=\sigma_Y^2$, $\mathbb E X_iY_i=\sigma_{XY}$ for all $i=1,\dots,n$.

_Problem:_

Assuming $\sigma_{XY}\neq0$, find matrices $A,B$ such that

$$A,B={\mathrm{arg}\max}_{A,B}\frac{|\mathbb E[(AX)^\top BY]|}{\sqrt{\mathbb E[(AX)^\top AX)]\mathbb E[(BY)^\top BY]}}.$$

_Partial Solution:_

Writing the $i,j$th entries for $A$ and $B$ respectively as $a_{ij},b_{ij}$, we have $AX=(\sum_ja_{1j}X_j,\dots,\sum_ja_{nj}X_j)^\top$ and $BY=(\sum_kb_{1k}Y_k,\dots,\sum_kb_{nk}Y_k)^\top$. Then

$$\mathbb E[(AX)^\top BY]=\mathbb E\sum_i(\sum_ja_{ij}X_j)(\sum_kb_{ik}Y_k)=\sigma_{XY}\sum_{ijk}a_{ij}b_{ik},$$

$$\mathbb E[(AX)^\top AX]=\sigma_X^2\sum_{ijk}a_{ij}a_{ik},$$

$$\mathbb E[(BY)^\top BY]=\sigma_Y^2\sum_{ijk}b_{ij}b_{ik}.$$

Setting $e=(1,\dots,1)^\top$, the problem can be restated as finding $A,B$ such that

$$A,B={\mathrm{arg}\max}_{A,B}\frac{|eA^\top Be|}{\sqrt{(eA^\top Ae)(eB^\top Be)}}$$

which does not depend on $\sigma_{XY}$.

Set $\alpha$ and $\beta$ equal to the row sums of $A$ and $B$ represented as column vectors (that is, $\alpha_i=\sum_ja_{ij}$ and $\beta_k=\sum_kb_{ik}$). From this we can see that any $A,B$ that solve the above problem must have row sum vectors that solve

$$\alpha,\beta={\mathrm{arg}\max}_{\alpha,\beta}\frac{|\alpha^\top\beta|}{\sqrt{(\alpha^\top\alpha)(\beta^\top\beta)}},$$

and the solution here is any $\alpha,\beta$ such that $\alpha=c\beta$ for some $c\in\mathbb R$. In particular, we can set $A=B=I$ with $c=1$. This suggests applying linear transformations to $X$ and $Y$ will at best preserve the known correlation, but never amplify it.
