---
title: "Mathematical Summary of SLiM Model"
output: pdf_document
---

To begin, one may start with a pair of interacting individual-based branching processes where individuals are associated with a trait $z\in\mathbb R$ and a geographic location $\pmb x\in\mathbb R^2$. Assuming semelparous life-cycles, we model mortality and reproduction simultaneously so that individuals replace themselves with a Poisson number of offspring between unit intervals of time. The lifetime expected number of offspring (which, since mortality is equal for all individuals, we refer to as fitness) is determined by the trait of the parent along with the traits of other individuals the parent interacts with. This is similar to the starting points taken by Week et. al. [-@Week2021b] in the derivation of a diffuse-coevolution model and by Week and Nuismer [-@Week2021] in the derivation of the offset-matching coevolution model, except neither of those models have a spatial component.

To model fitness, we first consider the effects of abiotic selection $\mathcal A_S$ and biotic selection $\mathcal B_S$ separately for host and parasite species ($S=H,P$). We decompose the effects of biotic selection into sources due to intraspecific competition $\mathcal B_S^c$ and interspecific parasitism $\mathcal B_S^p$ so that $\mathcal B_S=\mathcal B_S^c\mathcal B_S^p$. We will assume these effects multiply to produce the net fitness of an individual, $w_S=\mathcal A_S\mathcal B_S$. Set $w_{0,S}$ the maximum fitness possible for species $S$ in the absence of interspecific interactions and $\theta_S$ the abiotic optima trait value. Then, for either species, the multiplicative component of fitness due to abiotic stabilizing selection for an individual with trait $z$ at any location is

\begin{equation}
  \mathcal A_S(z)=w_{0,S}\exp\left(-\frac{A_S}{2}(\theta_S-z)^2\right).
\end{equation}

We assume competition occurs locally such that individuals that are geographically closer to each other induce stronger competition on one another than individuals that are further apart. This induces a form of local population regulation that prevents run-away population growth. Denoting the distance between two spatial positions $\pmb x$ and $\pmb y$ by $\|\pmb x-\pmb y\|$, $\pmb x^i_S$ the location of the $i$th individual in species $S$, and $n_S$ the number of individuals in species $S$, we model the effect of intraspecific competition on the $j$th individual as

\begin{equation}
  \mathcal B_S^c(\pmb x^j_S,\mathcal N_S)=\exp\left(-c_S\sum_{i\neq j}^{n_S}\exp\left(-\frac{\|\pmb x^j_S-\pmb x^i_S\|^2}{2\omega_S^2}\right)\right),
\end{equation}


$$\varrho(x)=\frac{\sum_i\chi(x-x_i)}{\int_U\chi(x-y)dy}$$

where $c_S$ denotes the strength of spatial competition, $\omega_S$ is the spatial scale of competition, and $\mathcal N_S$ denotes the abundance measure for species $S$. Because $\mathcal N_S(U,V)$ returns the number of individuals in species $S$ with trait values in $U\subset\mathbb R$ spatially located in the region $V\subset\mathbb R^2$, $\mathcal N_S$ captures the spatial locations and trait values of individuals and hence the trait distribution and abundance in any region of space for species $S$.

We model host-parasite interactions by assuming a probability of infection that is a function of trait values given an encounter has occurred. Assuming a host individual with trait $z_H$ encounters a parasite with trait $z_P$, the probability of infection $\alpha(z_H,z_P)$ can be written as

\begin{equation}
  \alpha(z_H,z_P)=\exp\left(-\frac{\gamma}{2}(z_H-z_P)^2\right),
\end{equation}

where $\gamma\geq0$ determines the sensitivity of this probability to differences in individual trait values. We will always assume weak sensitivity (ie, $\gamma\ll1$) so that $\alpha(z_H,z_P)\approx1-\gamma(z_H-z_P)^2/2$. We model the probability of encounter $\varepsilon$ similarly as a function of the geographical distance between individuals. Denoting $\iota\geq0$ the geographic scale of host-parasite interactions, we model the probability of encounter as

\begin{equation}
  \varepsilon(\pmb x_H,\pmb x_P)=\exp\left(-\frac{\|\pmb x_H-\pmb x_P\|^2}{2\iota^2}\right).
\end{equation}

We allow $\iota\ll1$ so that encounters may strongly depend on distance. Set $E_{ij}$ the Bernoulli random variable representing whether the $i$th parasite encounters the $j$th host and $I_{ij}$ the Bernoulli random variable representing the $i$th parasite infecting the $j$th host given their encounter. Assuming the parasite acquires the benefit $s_P\geq0$ and the host receives the cost $s_H\geq0$, the multiplicative effects of this single interaction on the fitnesses of the respective participants are $\exp(s_PE_{ij}I_{ij})$ and $\exp(-s_HE_{ij}I_{ij})$. Taking expectations provide

\begin{subequations}
  \begin{equation}
    \mathbb E[\exp(\pm s_SE_{ij}I_{ij})|E_{ij}]=(1-\alpha(z_H^j,z_P^i))+\alpha(z_H^j,z_P^i)\exp(\pm s_SE_{ij}),
  \end{equation}
  \begin{multline}
    \mathbb E[\exp(\pm s_SE_{ij}I_{ij})]=\left(1-\alpha(z_H^j,z_P^i)\right)+\alpha(z_H^j,z_P^i)\left((1-\varepsilon(\pmb x_H^j,\pmb x_P^i))+\varepsilon(\pmb x_H^j,\pmb x_P^i)\exp(\pm s_S)\right) \\
      =1+\alpha(z_H^j,z_P^i)\varepsilon(\pmb x_H^j,\pmb x_P^i)\left(\exp(\pm s_S)-1\right)\approx1\pm s_S\alpha(z_H^j,z_P^i)\varepsilon(\pmb x_H^j,\pmb x_P^i),
  \end{multline}
\end{subequations}

where the approximation holds when $s_H,s_P\ll1$, which we assume from hereon. Then, assuming every parasite can potentially infect every host, the components of biotic selection due to interspecific interactions for each species are approximated by

\begin{equation}
  \mathcal B_H^p(z_H^j,\pmb x_H^j,\mathcal N_P)\approx\prod_{i=1}^{n_P}1-s_H\alpha(z_H^j,z_P^i)\varepsilon(\pmb x_H^j,\pmb x_P^i),
\end{equation}

\begin{equation}
  \mathcal B_P^p(z_P^j,\pmb x_P^j,\mathcal N_H)\approx\prod_{i=1}^{n_H}1+s_P\alpha(z_H^i,z_P^j)\varepsilon(\pmb x^i_H,\pmb x^j_P).
\end{equation}

Using our weak biotic selection assumption $s_H,s_P\ll1$, it will be convenient to rewrite these expressions as

\begin{multline}
  \mathcal B_H^p(z_H^j,\pmb x_H^j,\mathcal N_P)\approx\exp\left(\int_{\mathbb R}\int_{\mathbb R^2}\ln\left(1-s_H\alpha(z_H^j,\zeta)\varepsilon(\pmb x_H^j,\pmb y)\right)\mathcal N_P(d\zeta,d\pmb y)\right) \\
    \approx\exp\left(-s_H\int_{\mathbb R}\int_{\mathbb R^2}\alpha(z_H^j,\zeta)\varepsilon(\pmb x_H^j,\pmb y)\mathcal N_P(d\zeta,d\pmb y)\right),
\end{multline}

\begin{multline}
  \mathcal B_P^p(z_P^j,\pmb x_P^j,\mathcal N_H)\approx\exp\left(\int_{\mathbb R}\int_{\mathbb R^2}\ln\left(1+s_P\alpha(\zeta,z_P^j)\varepsilon(\pmb y,\pmb x_P^j)\right)\mathcal N_H(d\zeta,d\pmb y)\right) \\
    \approx\exp\left(s_P\int_{\mathbb R}\int_{\mathbb R^2}\alpha(\zeta,z_P^j)\varepsilon(\pmb y,\pmb x_P^j)\mathcal N_H(d\zeta,d\pmb y)\right).
\end{multline}

To model mutation and spatial movement, we assume offspring trait values are normally distributed around their parental value [technically, this is done with breeding values, see Week et. al. -@Week2021b] and offspring locations are bivariate normal around their parental locations with i.i.d. displacements in the two spatial dimensions.

To take a diffusion limit of this individual-based process, we follow Week et. al. [-@Week2021b]. In particular, for the $k$th stage of rescaling, the time interval between generations is divided by $k$ (so it goes to zero as $k\to\infty$), the number of initial individuals $n_S(0)$ in each species $S=H,P$ is multiplied by $k$ (so $n_S(0)\to\infty$ as $k\to\infty$), the variances of mutation and dispersal are divided by $k$ (so both go to zero as $k\to\infty$), fitness for each individual is taken to the $1/k$th power (so individual fitness tends towards unity as $k\to\infty$), and the _mass_ of each individual is divided by $k$ (so initial population _mass_ remains $n_S(0)$ for all $k\geq1$). In particular, this last part of our rescaling implies

\begin{equation}
  \mathcal N^{(k)}_S(U,V)=\frac{1}{k}\sum_{i=1}^{kn_S(0)}\delta_{z_i,\pmb x_i}(U,V),
\end{equation}

where $z_i$ is the trait value of the $i$th individual, $\pmb x_i$ is its geographic location, and $\delta_{z_i,\pmb x_i}(U,V)=1$ if $z_i\in U$ and $\pmb x_i\in V$ and zero otherwise. Sufficient conditions under which the rescaled individual-based process $(\mathcal N^{(k)}_H,\mathcal N^{(k)}_P)$ converges to a population-level process $(\mathfrak N_H,\mathfrak N_P)$ as $k\to\infty$ are provided by Theorem 1 of Méléard and Roelly [-@Mlard1993]. In particular, their condition $(\mathscr H_1)$ requires the sequence $k\left(w^{1/k}_S(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right)$ to converge to the population growth rate $m_S(z,\pmb x,\mathfrak N_H,\mathfrak N_P)$ of the population-level process $\mathfrak N_S$ for species $S$. That is, population growth rates in the diffusion-limit are given by

\begin{equation}
  m_H(z,\pmb x,\mathfrak N_H,\mathfrak N_P)=\lim_{k\to\infty}k\left(w^{1/k}_H(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right),
\end{equation}
\begin{equation}
  m_P(z,\pmb x,\mathfrak N_P,\mathfrak N_H)=\lim_{k\to\infty}k\left(w^{1/k}_P(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right).
\end{equation}

For the host we have

\begin{multline}
  k\left(w^{1/k}_H(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right)\approx k\left(w^{1/k}_{0,H}\exp\left(-\frac{A_H}{2k}(z-\theta_H)^2-\frac{c_H}{k}\int_{\mathbb R^2}\chi_H(\pmb x,\pmb y)\mathcal N^{(k)}_H(\mathbb R,d\pmb y)\right.\right. \\
    \left.\left.-\frac{s_H}{k}\int_{\mathbb R}\int_{\mathbb R^2}\alpha(z,\zeta)\varepsilon(\pmb x,\pmb y)\mathcal N_P^{(k)}(d\zeta,d\pmb y)\right)-1\right),
\end{multline}

where we have set $\chi_S(\pmb x,\pmb y)=\exp\left(-\|\pmb x-\pmb y\|^2/2\omega_S^2\right)$. For large $k$, this is approximated by

\begin{multline}
  k\left(w^{1/k}_H(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right)\approx \left(kw^{1/k}_{0,H}-1-\frac{A_H}{2}(z-\theta_H)^2-c_H\int_{\mathbb R^2}\chi_H(\pmb x,\pmb y)\mathcal N^{(k)}_H(\mathbb R,d\pmb y)\right. \\
    \left. -s_H\int_{\mathbb R}\int_{\mathbb R^2}\alpha(z,\zeta)\varepsilon(\pmb x,\pmb y)\mathcal N_P^{(k)}(d\zeta,d\pmb y)\right).
\end{multline}

Then, setting $r_S=\ln w_{0,S}$ (the intrinsic growth rate for species $S$), we get

\begin{equation}
  m_H(z,\pmb x,\mathfrak N_H,\mathfrak N_P)=r_S-\frac{A_H}{2}(z-\theta_H)^2-c_H\int_{\mathbb R^2}\chi_H(\pmb x,\pmb y)\mathfrak N_H(\mathbb R,\pmb y)
    -s_H\int_{\mathbb R}\int_{\mathbb R^2}\alpha(z,\zeta)\varepsilon(\pmb x,\pmb y)\mathfrak N_P(d\zeta,d\pmb y).
\end{equation}

A similar expression for the parasite is also obtained. We now make the approximation that competition and selection are sufficiently weak relative to the intrinsic growth rate (i.e., $c_S,A_S,s_S\ll r_S$) so that spatial fluctuations in local abundance densities due to selection are small relative to average local abundance density for each species when the system has reached stationarity. This implies the population growth rates $m_H,m_P$ are near zero when the system has reached stationarity. With this approximation, we write $N_S$ as the abundance density for species $S$ so that $\mathfrak N_S(\mathbb R,U)=|U|N_S$, where $\mathbb R$ is given as the first argument to $\mathfrak N_S$ to include individuals with any trait value and $|U|$ is the area of the geographic region $U\subset\mathbb R^2$. In this case we have

\begin{equation}
  \int_{\mathbb R^2}\chi_S(\pmb x,\pmb y)\mathfrak N_S(\mathbb R,d\pmb y)=2\pi\omega_S^2N_S.
\end{equation}

The term capturing the effects of the host-parasite interaction has an integral across phenotypic space and an integral across geographic space. To simplify the geographic integral, set

\begin{equation}
  \mathfrak N^\iota_S(U,\pmb x)=\frac{\int_{\mathbb R^2}\varepsilon(\pmb x,\pmb y)\mathfrak N_S(U,d\pmb y)}{\int_{\mathbb R^2}\varepsilon(\pmb x,\pmb y)d\pmb y}=\sqrt{2\pi\iota^2}\int_{\mathbb R^2}\varepsilon(\pmb x,\pmb y)\mathfrak N_S(U,d\pmb y).
\end{equation}

This notation makes sense because $\varepsilon$ is a smooth integrable function and a convolution with such a function yields another smooth function. Furthermore, when $\iota\ll1$, $\int_V\mathfrak N^\iota_S(U,\pmb x)d\pmb x\approx\mathfrak N_S(U,V)$. Using our assumption that $\gamma\ll1$, the biotic and abiotic components cumulatively contribute quadratic selection. Hence, given that stabilizing abiotic selection is sufficiently strong relative to disruptive biotic selection on the host, trait distributions at any location will be approximately normal with mean and variance $\bar z_S(\pmb x),v_S(\pmb x)$ for species $S$ at location $\pmb x$. Then, assuming $\iota\ll1$, this implies

\begin{equation}
  \int_{\mathbb R^2}\int_{\mathbb R}\alpha(z,\zeta)\varepsilon(\pmb x,\pmb y)\mathfrak N_P(d\zeta,d\pmb y)
    = \frac{1}{\sqrt{2\pi\iota^2}}\int_{\mathbb R}\alpha(z,\zeta)\mathfrak N_P^\iota(d\zeta,\pmb x) 
    \approx \left(1-\frac{\gamma}{2}(z-\bar z_P(\pmb x))^2+v_P(\pmb x)\right)\frac{N_S}{\sqrt{2\pi\iota^2}}.
\end{equation}

Because selection is quadratic and abundance is constant, selection and drift decay phenotypic variance at a constant rate. From our assumption of Gaussian mutations, phenotypic variance also has a constant rate of input. We can therefore expect phenotypic variance for each species to eventually fluctuate stochastically around a spatially constant equilibrium. We thus further approximate by setting the phenotypic variances equal to those constant equilibria. We can therefore approximate the growth rates for each species as

\begin{subequations}\label{exact-growth}
  \begin{equation}
    m_H(z,\pmb x)\approx \rho_H-\frac{A_H}{2}(\theta_H-z)^2+\frac{B_H}{2}(\bar z_P(\pmb x)-z)^2,
  \end{equation}
  \begin{equation}
    m_P(z,\pmb x)\approx \rho_P-\frac{A_P}{2}(\theta_P-z)^2-\frac{B_P}{2}(\bar z_H(\pmb x)-z)^2,
  \end{equation}
\end{subequations}

where we have dropped the dependencies on $\mathfrak N_H,\mathfrak N_P$ for brevity and set $B_S=s_SN_S\gamma/\sqrt{2\pi\iota^2}$ and

\begin{subequations}
  \begin{equation}
    \rho_H=r_H+B_Hv_P/2-2\pi\omega_H^2c_HN_H,
  \end{equation}
  \begin{equation}
    \rho_P=r_P-B_Pv_H/2-2\pi\omega_P^2c_PN_P.
  \end{equation}
\end{subequations}
