---
title: "Referee Report on _Mutualists construct the ecological conditions that trigger the transition from parasitism_ preprint"
author: "Submitted to _Evolution_"
output: pdf_document
---

# Evaluation

I really enjoyed the introduction, motivation and review of previous work on the subject.

The addition of line-numbers would aid the review process.

## Issue with ~

- What happens if there's genetic correlations between $\alpha$ and $\epsilon$? are genetic correlations predicted to evolve during this transition?

- What's the significance of $\gamma_f$? Why is it interesting to include in the model? Why is it only applied to host and not symbiont?

- In regards to eqn (5), why should the host be affected by its mutualism cost when it's not engaged in the interaction? In the following paragraph the authors claim that the cost is a _developmental cost_. However, I'm not sure what this means. I would like to know some biological examples that motivate this reasoning. The motivation for the competition component of the model beneath Figure A2 is a good example of what I would hope to see for the developmental cost component of the model.

- It seems like setting the maximum expected offspring number of solitary hosts ($f^{sh}_{\max}$) to 0.5 is problematic for this study. A population where individuals have at most 0.5 offspring on average is not viable (population size is expected to half each generation). Hence, it seems that the conditions for mutualism to evolve are manifest in this parameter. I would be curious to understand how the results change when the solitary host population is (more) viable. In particular, what is the threshold maximum expected offspring number for solitary hosts at which mutualism does not evolve? At least a ballpark estimate would be interesting (e.g., greater than one). Alternatively, demonstrating that mutualism usually does not evolve when maximum expected offspring number of solitary hosts is fixed to 0.5, but some other important parameter has been modified, would be sufficient to demonstrate that simulations are not rigged to force mutualism to evolve.

- Section titled _Parasitic system and transition_ under the model description: I am having a hard time believing that an equilibrium population exists in the absence of mutualism

## Notation and model presentation

## Line-by-line comments/suggestions

- On page two, beginning of third paragraph: "With respect to altruism" should be "With respect to mutualism"?

- Second paragraph under the subsection titled _Fecundity rate and mutualism/parasitism_: Is "strong mutualism" something that has been defined elsewhere? If so, please cite that source. Otherwise, it seems like a reasonable term to describe the form of mutualism being modeled.

- Third paragraph under the subsection titled _Fecundity rate and mutualism/parasitism_: "We note interactions traits of the host and symbiont..." should be "We __denote__ interaction traits of the host and symbiont __by__...".

- The section on mutation in the model description: What rates did you use in the exponential distritbution for each trait and for each species?

- Section on dispersal: The cost of global dispersal $d$ has already been used as a parameter limiting the size of mutations. Please pick a different symbol to improve notational clarity.

- Section on competition: It would be helpful to state that competition among hosts occurs globally early in the description. I was expecting competition to occur locally and am actually a bit surprised global competition helps the transition to mutualism.

### Appendix A1

- The term _fecundity rate_ makes it sound like a continuous time model where offspring are produced at a specific rate. This confused me since the authors develop a discrete-time model. I think replacing the term _fecundity rate_ with something like _offspring number_ would be less confusing.

- There appears to be a typo in equations (2). In particular, setting $\alpha_i=1$ for either $i=h$ or $i=s$ does not return $f_{I,\max}$. Instead, if the authors dropped the second $f^i_{I,\min}$ appearing between $c_f^i$ and $\alpha_i$, these equations would return $f_{I,\max}$. It's unclear whether this was a type and if so whether the simulations inherited it.

- Figure A1: From this figure it appears that symbionts do not disperse. However, it seems like they should disperse freely since they are not vertically transmitted.

- Caption for Figure A1: Instead of calling it a _numerical algorithm_, please refer to it as a simulation or, even better, an individual-based or agent-based simulation. Although it technically is a numerical algorithm, simulation is the more colloquial phrase.

- Sentence following Figure A1: This sentence is redundant and confusing. I think the point would be clarified without it.

- Eqn (6): An additional sentence explaining the relevance of the _mutualism/parasitism threshold_ would be helpful.

- Eqn (7): Just a small point on notation. The spatial scale parameter $c_s$ looks like it should be affiliated with the symbiont. Something like $\psi_h$ may be less confusing.

## Appendix ~
