---
output: pdf_document
---

# The role of geography in patterns of local adaptation and the spatial scale of coevolution (SPDE project)

_Abstract_: Previous work modelling the consequences of interactions between gene-flow, random genetic drift and coevolution on local adaptation in host-parasite systems have made use of metapopulation models where geography is discretized and dispersal is global. These studies generally conclude that an increased rate of gene-flow for the parasite relative to the host yields parasite local adaptation. The colloquial explanation for this result is that increased dispersal can lead to increased genetic variance and thus promote adaptive capacity. However, this explanation ignores the effect of continuous versus discrete geography and how patterns of limited versus global dispersal interact with drift to determine which species is locally adapted. To close this gap we study a phenotypic model of host-parasite coevolution in continuous space with finite local population densities. We find the parasite is locally adapted to its host when its average dispersal distance is shorter than the average dispersal distance of the host. Performing a similar analysis on a metapopulation model of host-parasite trait coevolution where dispersal is global and genetic variance is held constant, we recover the classical result described above. This highlights the role of geography and in particular suggests a subtle distinction between the effects of dispersal rate and dispersal distance on parasite local adaptation.

Summaries of

- _Introduction_: Introduce concepts of host parasite coevolution, limited vs global dispersal and local adaptation Review relevant work on spatial dynamics of host-parasite coevolution and the determinants of the identity of the locally species. Note the dearth of studies exploring the consequences of continuous space. Motivate the possibility that limited dispersal in continuous space may interact with drift to yield a different result from the classic one. Outline our approach to study local adaptation continuous space. Mention this approach naturally leads to a notion for the spatial scale of coevolution. Briefly summarize our methods and findings.

- _Methods_: Being as light as possible with math, explain the coevolutionary model and how we extend the definition of local adaptation to continuous space. Since the continuous space local adaptation metric involves the spatial cross-covariance function, describe how we obtain this function. Mention how this function can be used to define a notion for the spatial scale of coevolution. Describe how we obtain our results on the identity of the locally adapted species as a function of the ratio of dispersal distances between the species. Finish by describing the discrete geography model (and reference the entry in scotts book where he studies it).

- _Results_: Continuing to be light on the math, summarize our findings for the spatial intraspecific autocovariance functions. In particular, show that the notion for spatial scale of intraspecific variation suggested by our model coincides with that of slatkin (1978). Discuss things like what happens in the limit of infinite dispersal distance (collocated variance collapses to zero because the population becomes panmictic and therefore infinite in size). Go on to present the collocated spatial cross-covariance and its simplifications in the cases of equal intraspp scales and drastically different intraspp scales. Then present our notion for the spatial scale of coevolution and use the cases under which the marginal cross-cov simplifies to motivate presenting the cross-scale under these same simplifications. Finally, present our result on local adaptation as a function of relative dispersal distance.

- _Discussion_: One paragraph discussing our results on local adaptation and how they actually don't contradict classical results. Include some remarks on Slatkins78 and Hadfield16. One paragraph on how our work presents a novel spatial statistical model of cross-covariance. One paragraph on caveats. One paragraph on future directions.

- _Conclusion_: Once again, briefly summarize our results and approach taken. Provide a single sentence on previous work, a single sentence on caveats, and a single sentence on future directions. End with a nice, but likely unsubstantial sentence about studying local adaptation in the wild.

# SLiM Projects

## _Houston, we have a problem_ subproject

Simulate $n$ replicated data sets for:

  - four combinations of dispersal distances (short/long)
  
    - neutral scenario (no interaction)
    
    - four combinations of selection strengths (weak/strong)
    
      - four combinations of architecture (monogenic/oligogenic)
      
        - parasitic/mutualistic

That's $4n$ neutral sims + $128n$ non-neutral sims. Assuming each sim takes ten minutes implies a total of $2.2n$ hours if run in serial.

With these data apply the nuismerian t-test approach and:

  - compute distribution of type-1 error rates for each neutral scenario
  
  - compute distributions of type-1 and type-2 error rates for each non-neutral scenario

Make four nested four panel figures for each error rate where the four plots correspond to the monogenic/oligogenic combinations, the exterior panels for each plot correspond to weak/strong coevolution and the plots in each panel display the estimated error rate as bivariate function of dispersal distances.

Conclude by describing scenarios where the t-test approach fails due to spurious interspecific correlations generated by spatially autocorrelated allele frequencies. Identify scenarios where the method works. Compare with Dybdal-Jenkins-Nuismer ppr.

## _Genomic signal of coevolution in continuous space_ subproject

Find statistics with high power and low false-positive rates:

  - Do community detection algorithms detect larger communities for the causal loci than for spuriously correlated neutral loci?
  
  - Does analyzing the ild matrix at different resolutions of spatial discretization tell us anything?
  
  - If we make parasites move to host locations for infection, can this spatial paring be used to obtain a "cleaner" signal than spatial discretization methods?
  
  - Do the cca-spatial whitening stuff and see what pops out.