import burnin as bp
import genotypearrays as ga
import ild
import pandas as pd
import subprocess
import os

# os.chdir("../spacecomp")
# # in case you need to reload module
import importlib
importlib.reload(ild) # example use


#
# this script first populates the subfolder structure that organizes
# parameter combinations and replicates per parameter combo
# with parameter files that input to msprime and slim
# then it will run the makeILD function in parallel across all
# parameter combos and replicates, but just ncpu at a time
# in turn, the makeILD function populates the subfolder structure
# with initial tree seqs generated by msprime, with final tree seqs
# generated by slim, separate genotype arrays for causal and neutral
# mutations, and, finally, causal, neutral and combined ild matrices
#

# burn-in parameters
bprs = pd.read_csv("bparams.csv", sep=",")

# slim parameters
sprs = pd.read_csv("slim-pars.csv", sep=",")

def makeILD(msprpth,datapth):

    # do the burn-in
    bp.burnin(msprpth,datapth)

    # run the slimulation calling parameter file in specified subfolder
    slmcmd = """slim -d "parfname='"""+msprpth+"""slim-pars.csv'"  -d "trefldr='"""+datapth+"""'" hp.slim"""
    subprocess.run(slmcmd, shell=True)

    # add neutral mutations and export genotype arrays
    ga.genotypeArrays(datapth)

    # compute ild matrices and save to specified subfolder  
    ild.ild(datapth,msprpth)

def makeILD_nonspatial(msprpth,datapth):

    # do the burn-in
    bp.burnin(msprpth,datapth)

    # run the slimulation calling parameter file in specified subfolder
    slmcmd = """slim -d "parfname='"""+msprpth+"""slim-pars.csv'"  -d "trefldr='"""+datapth+"""'" hp-nonspatial.slim"""
    subprocess.run(slmcmd, shell=True)

    # add neutral mutations and export genotype arrays
    ga.genotypeArrays(datapth)

    # compute ild matrices and save to specified subfolder  
    ild.ild(datapth,msprpth)

#
# pseudo-nonspatial sim
#

superfolder = os.path.expanduser("~/gsccs-data/spacecomp/nonspatial/")
sprs["W₀ₚ"] = 0.8
sprs["cₚ"]  = 0.1
bprs.to_csv(superfolder+"/bparams.csv", index=False)
sprs.to_csv(superfolder+"/slim-pars.csv", index=False)
makeILD_nonspatial(superfolder,superfolder)

# ild.ild(superfolder,superfolder)

#
# spatial sim
#

superfolder = os.path.expanduser("~/gsccs-data/spacecomp/spatial/")
sprs["W₀ₚ"] = 1.0
sprs["cₚ"]  = 0.075
bprs.to_csv(superfolder+"/bparams.csv", index=False)
sprs.to_csv(superfolder+"/slim-pars.csv", index=False)
makeILD(superfolder,superfolder)

ild.ild(superfolder,superfolder)