---
title: "Mapping Simulation Model Variables to SPDE Model Variables"
header-includes:
  - \usepackage{amsmath}
  - \usepackage{dutchcal}
  - \usepackage{mathrsfs}
  - \usepackage{csquotes}
  - \usepackage{textcomp}
  - \usepackage[T3,T1]{fontenc}
  - \DeclareSymbolFont{tipa}{T3}{cmr}{m}{n}
  - \DeclareMathAccent{\invbreve}{\mathalpha}{tipa}{16}
output: pdf_document
---

### Strength of Biotic Selection Given a Single Encounter

Start by considering the component of fitness due to biotic interactions $W_S^{(B)}$ used in the individual-based model:

$$W_S^{(B)}(z_H,z_P)=(\iota_S)^\chi, \ \chi\sim\mathrm{Bern}\big(\pi(z_H,z_P)\big)$$

where the probability of infection is

$$\pi(z_H,z_P)=\pi_{\max}\exp\left(-\frac{\gamma}{2}(z_H-z_P)^2\right).$$

Can rewrite $W_S^{(B)}=\exp(\chi\ln\iota_S)$ and thus $\mathbb E[W_S^{(B)}]$ takes the form of a moment-generating function. Using the known mgf of a Bernoulli rv, we have

$$w_S^{(B)}=\mathbb E[W_S^{(B)}]=\big(1-\pi(z_H,z_P)\big)+\pi(z_H,z_P)e^{\ln\iota_S}=\Big(1+(\iota_S-1)\pi(z_H,z_P)\Big).$$

$$m_S(z_H,z_P)=\lim_nn(w_S^{1/n}-1)=\lim_nn\Big((w_S^{(A)})^{1/n}(w_S^{(B)})^{1/n}-1\Big)=\ln w_S^{(A)}+\ln w_S^{(B)}.$$

Assuming weak biotic selection so that $\gamma\ll1$ we have

$$w_S^{(B)}\approx\Big(1+(\iota_S-1)\pi_{\max}\left(1-\frac{\gamma}{2}(z_H-z_P)^2\right)\Big).$$

If we further assume that $|\iota_S-1|\ll1$, then

$$\ln w_S^{(B)}\approx\pi_{\max}(\iota_S-1)\left(1-\frac{\gamma}{2}(z_H-z_P)^2\right)=\pi_{\max}(\iota_S-1)-\frac{\gamma\pi_{\max}(\iota_S-1)}{2}(z_H-z_P)^2.$$

Under our SPDE model, the growth rate utilized took the form

$$\bar m_S=r_S-\frac{A_S}{2}(\theta_S-\bar z_S)^2\pm\frac{B_S}{2}(\bar z_H-\bar z_P)^2,$$

where the biotic term is added for $S=H$ and subtracted for $S=P$. Relating the two, we see the $\pi_{\max}(\iota_S-1)$ term out front can be accounted for by the intrinsic growth rate $r_S$ leaving

$$B_S\approx\gamma\pi_{\max}|\iota_S-1|.$$

#### Parasite Biotic Selection

Since parasites may not be close enough to a host to experience an encounter, we need to modify our calculations. Given host density $\rho_H$, we can model the number of observed hosts within a region of radius $R$ as Poisson with parameter $N_H(R)=\pi R^2\rho_H$. We can then approximate the probability that no hosts will be within a given region of radius $R$ as

$$\mathbb P_R(\text{no hosts} \ | \ \rho_H)=e^{-N_H(R)}.$$

Then, since for infection to occur there needs to be a host present within the interaction radius $R_\iota$ of the parasite, the infection probability for the parasite is replaced by

$$\pi(z_H,z_P)\to\big(1-e^{-N_H(R_\iota)}\big)\pi(z_H,z_P)$$

Then, repeating the same calculation as above, we find the strength of biotic selection on the parasite can be parameterized as

$$B_P\approx\gamma\pi_{\max}(\iota_P-1)\big(1-e^{-N_H(R_\iota)}\big).$$

Then, averaging over local host and parasite populations with respective means and variances $\bar z_H,\bar z_P,v_H,v_P$ we find the local parasite growth rate

$$\bar m_P\approx\pi_{\max}(\iota_P-1)\big(1-e^{-N_H(R_\iota)}\big)-B_P(v_H+v_P)/2-B_P(\bar z_H-\bar z_P)^2/2$$

which implies the biotic component of the innate growth rate can be parameterized as

$$r_P^{(B)}\approx\pi_{\max}(\iota_P-1)\big(1-e^{-N_H(R_\iota)}\big)-B_P(v_H+v_P)/2.$$

#### Host Biotic Selection

Since hosts may not be close enough to a parasite to experience an encounter or may experience multiple encounters if there are several parasites nearby (which will depend on host density), we need to modify our calculations. Following the above approach, we can model the number of parasites within the interaction radius $R_\iota$ of the host as Poisson with parameter $N_P(R_\iota)=\pi R_\iota^2\rho_P$. For parasite $i$ within this region, we model the number of hosts within their interaction radius $n_i$ and compute the probability of encounter with the focal host as the inverse of this number, $1/n_i$. We then accumulate the total number of encounters times their probabilities of infection. We will denote the $i$th parasites trait by $z_i$ and the focal hosts trait by $z_H$.

The probability of $K$ parasites within the interaction radius of the focal host is

$$\mathbb P(K)=\frac{1}{K!}N_P^K(R_\iota)^Ke^{-N_P(R_\iota)}.$$

For the $i$th parasite, the probability of $n_i$ hosts within its interaction radius is

$$\mathbb P(n_i)=\frac{1}{n_i!}N_H^{n_i}(R_\iota)e^{-N_H(R_\iota)}.$$

Denote the rv determining whether parasite $i$ encounters the focal host by $\varepsilon_i\sim\mathrm{Bern}(1/n_i)$ and the probability that parasite $i$ infects the focal host by $\chi_i\sim\mathrm{Bern}(\pi(z_H,z_i))$. Then the cumulative fitness effect of interactions with parasites on the focal host is given by

$$(\iota_H)^{\sum_{i=1}^K\chi_i\varepsilon_i}.$$

We can model infection from parasite $i$ as a Bernoulli trial with parameter $\pi(z_H,z_i)/n_i$. Then, assuming these trials are independent, the moment generating function of the sum $\sum_{i=1}^K\chi_i\varepsilon_i$ is just the product the moment generating functions of each trial:

$$w_H^{(B)}=\mathbb E[(\iota_H)^{\sum_{i=1}^K\chi_i\varepsilon_i}]=\prod_{i=1}^K\Big(1+(\iota_H-1)\pi(z_H,z_i)/n_i\Big).$$

Using our small $\gamma$ approximation again leads to

$$w_H^{(B)}\approx\prod_{i=1}^K\Big(1+(\iota_H-1)\frac{\pi_{\max}}{n_i}\left(1-\frac{\gamma}{2}(z_H-z_i)^2\right)\Big).$$

Now assuming $|\iota_H-1|\ll1$, we have

$$\ln w_H^{(B)}\approx\sum_{i=1}^K(\iota_H-1)\frac{\pi_{\max}}{n_i}\left(1-\frac{\gamma}{2}(z_H-z_i)^2\right)=\sum_{i=1}^K(\iota_H-1)\frac{\pi_{\max}}{n_i}-(\iota_H-1)\frac{\pi_{\max}}{n_i}\frac{\gamma}{2}(z_H-z_i)^2.$$

Setting $\bar z_P, v_P$ as the local parasite mean trait and trait variance respectively, we further approximate with

$$\ln w_H^{(B)}\approx K\left((\iota_H-1)\frac{\pi_{\max}}{n_i}-(\iota_H-1)\frac{\pi_{\max}}{n_i}\frac{\gamma}{2}[(z_H-\bar z_P)^2+v_P]\right).$$

Finally, we approximate $K$ and the $n_i$ with their respective expectations $N_P(R_\iota)$ and $N_H(R_\iota)$. Hence, the strength of biotic selection on the host can be expressed as

$$B_H\approx N_P(R_\iota)\gamma(\iota_H-1)\frac{\pi_{\max}}{N_H(R_\iota)}=\gamma\pi_{\max}(\iota_H-1)\frac{\rho_P}{\rho_H}.$$

Averaging over the local host population with trait variance $v_H$ results in the innate growth rate

$$r_H^{(B)}\approx\pi_{\max}(\iota_H-1)(1-\gamma v_P/2)\frac{\rho_P}{\rho_H}-B_H(v_H+v_P)/2.$$

### Abiotic component of growth rate

For species $S$, the abiotic component of the individual fitness function is $w^{(A)}_S(z)=\alpha_S\exp\left(-\frac{A_S}{2}(\theta_S-z)^2\right)$. In the diffusion-limit, the resulting growth rate averaged across a local population is $m^{(A)}_S=\ln\alpha_S-A_S[(\theta_S-\bar z_S)^2+v_S]/2$, where $\bar z_S$ is the local mean trait and $v_S$ is the local phenotypic variance around the mean. Hence, in terms of the SPDE model parameterization we have $r_S=r_S^{(A)}+r_S^{(B)}$ where $r_S^{(B)}$ is as above and $r_S^{(A)}=\ln\alpha_S-A_Sv_S/2$.

### Additive Genetic Variance

At equilibrium and under weak coevolution, we have the approximation

$$G_P\approx \sqrt{\mu_P/(A_P+B_P)}$$

$$G_H\approx \sqrt{\mu_H/(A_H-B_H)}$$

- These $G$'s are measured at some local scale. Perhaps measured by dispersal distance $\sigma$?

### Expressed Phenotypic Variation

This should always be approximately true, especially for large population sizes

$$v_S\approx G_S+E_S.$$

However, which $v$ and which $G$ depends on the scale considered. The 'local population scale' may be determined by dispersal distance, but interactions occur at a particular radius. So when averaging over potential interaction partners, the appropriate $v$ and $G$ should be measured at the scale of the interaction radius.

### Population Density

Given $n$ individuals within a radius $R_S$, the fitness of an individual in species $S$ will be attenuated by $(\kappa_S)^n$. This corresponds to an additive effect on growth rate of $-n\ln\kappa_S$. Then, at the scale on which competition occurs the equilibrium expectation is

$$\rho_P\approx \frac{-1}{\ln\kappa_P}\Big(\bar m_P-\frac{1}{2}\sqrt{\mu_P(A_P+B_P)}\Big)$$

$$\rho_H\approx \frac{-1}{\ln\kappa_H}\Big(\bar m_H-\frac{1}{2}\sqrt{\mu_S(A_H-B_H)}\Big)$$

where

$$\bar m_S=r_S-\frac{A_S}{2}(\theta_S-\bar z_S)^2\pm\frac{B_S}{2}(\bar z_H-\bar z_P)^2,$$

$$r_H=\ln\alpha_H-A_Hv_H/2+\pi_{\max}(\iota_S-1)(1-\gamma v_P/2)\frac{\rho_P}{\rho_H}+B_H(v_H+v_P)/2,$$

$$r_P=\ln\alpha_P-A_Pv_P/2+\pi_{\max}(\iota_P-1)\big(1-e^{-N_H(R_\iota)}\big)-B_P(v_H+v_P)/2,$$

$$B_H\approx\gamma\pi_{\max}(1-\iota_H)\frac{\rho_P}{\rho_H}$$

$$B_P\approx\gamma\pi_{\max}(\iota_P-1)\big(1-e^{-N_H(R_\iota)}\big).$$

- Need to test these predictions against simulations...

```{r echo=F, warning=FALSE}
host_df1 = read.csv("julia/ibm/host_df1.csv");
para_df1 = read.csv("julia/ibm/para_df1.csv");

# to get rho_S, drop a few disks of radius R_S
# make sure they don't intersect
# then estimate rho_S by average density of inds in each disk

ndisk = 20
RH = 0.005	# competition radii
RP = 0.005

# pick their centers, calulate distance & count individuals
centersH = matrix(runif(2*ndisk, min=RH, max=1-RH),ndisk,2)
centersP = matrix(runif(2*ndisk, min=RP, max=1-RP),ndisk,2)
distsH = matrix(0,ndisk,ndisk)
distsP = matrix(0,ndisk,ndisk)
for(i in 1:ndisk){
  for(j in 1:ndisk){
    distsH[i,j] = sqrt( sum((centersH[i,]-centersH[j,])^2) )
    distsP[i,j] = sqrt( sum((centersP[i,]-centersP[j,])^2) )
  }
}
indsH = list()
indsP = list()
nindsH = rep(0,3)
nindsP = rep(0,3)
for(i in 1:ndisk){
  indsH[[i]] = which(rowSums((cbind(host_df1$x1,host_df1$x2)-centersH[i,])^2)<RH)
  indsP[[i]] = which(rowSums((cbind(para_df1$x1,para_df1$x2)-centersP[i,])^2)<RP)
  nindsH[i] = length(indsH[[i]])
  nindsP[i] = length(indsP[[i]])
}

# ensures they're not overlapping, not empty and not too close to the edge
mH = min(distsH[upper.tri(distsH)])
mP = min(distsP[upper.tri(distsP)])
while(mH<(2*RH) | min(nindsH)==0){
  centersH = matrix(runif(2*ndisk, min=RH, max=1-RH),ndisk,2)
  for(i in 1:ndisk){
   for(j in 1:ndisk){
      distsH[i,j] = sqrt( sum((centersH[i,]-centersH[j,])^2) )
    }
  }
  mH = min(distsH[upper.tri(distsH)])
  for(i in 1:ndisk){
    indsH[[i]] = which(rowSums((cbind(host_df1$x1,host_df1$x2)-centersH[i,])^2)<RH)
    nindsH[i] = length(indsH[[i]])
  }
}
while(mP<(2*RP) | min(nindsP)==0){
  centersP = matrix(runif(2*ndisk, min=RP, max=1-RP),ndisk,2)
  for(i in 1:ndisk){
   for(j in 1:ndisk){
      distsP[i,j] = sqrt( sum((centersP[i,]-centersP[j,])^2) )
    }
  }
  mP = min(distsP[upper.tri(distsP)])
  for(i in 1:ndisk){
    indsP[[i]] = which(rowSums((cbind(para_df1$x1,para_df1$x2)-centersP[i,])^2)<RP)
    nindsP[i] = length(indsP[[i]])
  }
}

zbarH = rep(0,ndisk)
GH = rep(0,ndisk)
zbarP = rep(0,ndisk)
for(i in 1:ndisk){
  zbarH = mean(host_df1$trait[indsH[[i]]])
  
  zbarP = mean(para_df1$trait[indsP[[i]]])
}

pi = 3.14159

rhoH_hat = mean(nindsH) #/(pi*RH^2)
rhoP_hat = mean(nindsP) #/(pi*RP^2)

rhoH_var = var(nindsH) #/(pi*RH^2)
rhoP_var = var(nindsP) #/(pi*RP^2)

gamma = 0.1
pimax = 1.0
Ri = 0.01

iotaP = 1.1
alphP = 1.2
kappaP = 0.98
muP = 0.1
EP = 0.001
AP = 0.002

iotaH = 0.99
alphH = 1.4
kappaH = 0.975
EH = 0.001
muH = 0.1
AH = 0.002

minthis = function(X){
  
  rhoH = X[1]
  rhoP = X[2]
  BP = gamma*pimax*(iotaP-1)*(1-exp(-2*pi*Ri^2*rhoH))
  vP = EP + sqrt(muP/(AP+BP))
  BH = -gamma*pimax*(iotaH-1)*rhoP/rhoH 
  
  rP = log(alphP)+pimax*(iotaP-1)*(1-exp(-2*pi*Ri^2*rhoH))
  rH = log(alphH)+pimax*(iotaH-1)*(1-gamma*vP/2)*rhoP/rhoH
  
  out = c((rhoH+(rH-0.5*sqrt(muH*abs(AH-BH)))/log(kappaH))^2,
          (rhoP+(rP-0.5*sqrt(muP*(AP+BP)))/log(kappaP))^2 )
  
  return(sqrt(sum(out)))
}

num_rho = optim(rexp(2,1/10),minthis)

rhoH = num_rho$par[1] #/(2*pi*RH^2)
rhoP = num_rho$par[2] #/(2*pi*RP^2)

BP = gamma*pimax*(iotaP-1)*(1-exp(-2*pi*Ri^2*rhoH))
vP = EP + sqrt(muP/(AP+BP))
BH = -gamma*pimax*(iotaH-1)*rhoP/rhoH 
vH = EH + sqrt(muH/(AH-BH))
rP = log(alphP)+pimax*(iotaP-1)*(1-exp(-2*pi*Ri^2*rhoH))
rH = log(alphH)+pimax*(iotaH-1)*(1-gamma*vP/2)*rhoP/rhoH

ExpObs.df = data.frame(Parameter=c("host density","parasite density"), Expectation=c(rhoH, rhoP), Observation=c(rhoH_hat, rhoP_hat))

print(ExpObs.df)
```


