---
title: The Phenotypic Signature of Host-Parasite Coevolution in Continuous Space
authors:
  - name: Bob Week
    department: Integrative Biology
    affiliation: Michigan State University
    location: East Lansing, MI 48824
    email: weekrobe@msu.edu
  - name: Gideon Bradburd
    department: Integrative Biology
    affiliation: Michigan State University
    location: East Lansing, MI 48824
    email: bradburd@msu.edu
abstract: |
  Here we identify the phenotypic signature of host-parasite coevolution in continuous space.
keywords:
  - blah
  - blee
  - bloo
  - these are optional and can be removed
bibliography: references.bib
header-includes:
  - \usepackage{amsmath}
output: 
  rticles::arxiv_article:
    keep_tex: true
---

# Introduction

Space is hypothesized to play a fundamental role in the coevolutionary process. In particular, the combined effects of local co-adaptation and spatial movement are thought to produce complex spatial patterns of matched and mismatched traits. However, theoretical studies investigating the spatial signal of coevolution have for the most part restricted themselves to understanding patterns of spatial correlation using spatially implicit models. Hence, the fine-grained details that can be produced in spatially explicit settings have yet to be understood. Here we close this gap in the context of host-parasite coevolution using continuous-space quantitative genetic models. In particular, we study the autocorrelations of mean traits within species and the cross-correlation of mean traits between species when trait dynamics are driven by (1) random genetic drift, gene-flow and spatially homogeneous abiotic stabilizing selection, (2) random genetic drift, gene-flow, spatially homogeneous stabilizing selection and unilateral adaptation of the host species, (3) random genetic drift, gene-flow and unilateral adaptation of the parasite species and (4) random genetic drift, gene-flow, stabilizing selection and host-parasite coevolution. By comparing patterns of spatial autocorrelation and cross-correlation in these four scenarios we are able to elucidate the signature of coevolution in comparison to underlying non-coevolutionary processes.

# The Model

## Fitness

The host is denoted $H$ and the parasite $P$. Individual trait values of hosts and parasites are respectively denoted by $z_H,z_P\in\mathbb R$. Assuming a trait-matching model, where host fitness is minimized and parasite fitness is maximized when $z_H=z_P$, we have the following two fitness functions:

\begin{subequations}\label{fit}
  \begin{equation}
    w_H(z_H,z_P)\propto \exp\left(-\frac{A_H}{2}(\theta_H-z_H)^2+\frac{B_H}{2}(z_P-z_H)^2\right),
  \end{equation}
  \begin{equation}
    w_P(z_P,z_H)\propto \exp\left(-\frac{A_P}{2}(\theta_P-z_P)^2-\frac{B_P}{2}(z_H-z_P)^2\right),
  \end{equation}
\end{subequations}

where $A_H,A_P>0$ capture the strengths of abiotic stabilizing selection, $\theta_H,\theta_P\in\mathbb{R}$ are the abiotic optimal phenotypes and $B_H,B_P>0$ capture the strengths of biotic selection experienced by each species.

## Non-spatial Dynamics

Using a standard approach, we use the above fitness functions to derive the following non-spatial coevolutionary model:

\begin{subequations}\label{non-spatial}
  \begin{equation}
    \frac{d\bar z_H}{dt}=G_HA_H(\theta_H-\bar z_H)-G_HB_H(\bar z_P-\bar z_H),
  \end{equation}
  \begin{equation}
    \frac{d\bar z_P}{dt}=G_PA_P(\theta_P-\bar z_P)+G_PB_P(\bar z_H-\bar z_P),
  \end{equation}
\end{subequations}

where $G_H,G_P>0$ denote the additive genetic variances of each species. In this linear set of equations, when abiotic stabilizing selection is absent ($A_H=A_P=0$), the parasite mean trait $\bar z_P$ evolves to match the host mean trait $\bar z_H$. Simultaneously $\bar z_H$ evolves away from $\bar z_P$. In particular, when $\bar z_H>\bar z_P$, the host mean trait will evolve upwards. Similarly, when $\bar z_H<\bar z_P$, the host mean trait will evolve downwards. This and related models have been thoroughly studied by Sergey Gavrilets and others. For the case when $A_H=A_P=0$ two possible outcomes have been demonstrated. First, when $G_PB_P>G_HB_H$ so that the parasite evolves faster than the host, the system asymptotically evolves to the equilibrium $\bar z_H=\bar z_P$. Second, when $G_PB_P<G_HB_H$ so that the host evolves faster than the parasite, there is no stable equilibrium. This implies the host evolves to escape the interaction. In the case when $A_H,A_P\neq0$ limit cycles can emerge.

## Space

In this case mean traits become functions of spatial variables (eg., $\bar z_H(x),\bar z_P(x)$ for $x\in\mathbb R$ and $\bar z_H(x_1,x_2),\bar z_P(x_1,x_2)$ for $(x_1,x_2)\in\mathbb R^2$). As a first step, we assume all model parameters are spatially homogeneous. If we assume interactions occur locally (individuals interact only when they 'collide') and abundance densities are spatially homogeneous, then we can obtain the following continuous space model:

\begin{subequations}\label{deterministic}
  \begin{equation}
    \frac{\partial\bar z_H}{\partial t}=G_HA_H(\theta_H-\bar z_H)-G_HB_H(\bar z_P-\bar z_H)+\frac{D_H}{2}\Delta\bar z_H,
  \end{equation}
  \begin{equation}
    \frac{\partial\bar z_P}{\partial t}=G_PA_P(\theta_P-\bar z_P)+G_PB_P(\bar z_H-\bar z_P)+\frac{D_P}{2}\Delta\bar z_P,
  \end{equation}
\end{subequations}

where $D_H,D_P>0$ are dispersal rates for each species and $\Delta$ is the diffusion operator representing spatial movement. In particular, $\Delta=\frac{\partial^2}{\partial x^2}$ in one-dimensional space and $\Delta=\frac{\partial^2}{\partial x_1^2}+\frac{\partial^2}{\partial x_2^2}$ in two-dimensional space.

## Random Genetic Drift

To incorporate the effects of random genetic drift, we should be able to justify the following SPDE model:

\begin{subequations}\label{spde}
  \begin{equation}
    \frac{\partial\bar z_H}{\partial t}=G_HA_H(\theta_H-\bar z_H)-G_HB_H(\bar z_P-\bar z_H)+\frac{D_H}{2}\Delta\bar z_H+\sqrt\frac{G_H}{N_H}\dot W_H,
  \end{equation}
  \begin{equation}
    \frac{\partial\bar z_P}{\partial t}=G_PA_P(\theta_P-\bar z_P)+G_PB_P(\bar z_H-\bar z_P)+\frac{D_P}{2}\Delta\bar z_P+\sqrt\frac{G_P}{N_P}\dot W_P,
  \end{equation}
\end{subequations}

where $N_P,N_H$ are the local abundance densities (here assumed to be constant in space and time) and $\dot W_H,\dot W_P$ are space-time white noise processes. This SPDE model may possess some major benefits over more traditional continuous-space models of population genetics. In particular, it is a simple extension of the stochastic heat equation, which is known to admit solutions in dimensions one, two and three.

# Methods

To study the continuous-space signature of coevolution, we can start with an analytical approach. However, if the corresponding calculations prove to be analytically intractable or time costly, we can employ simulation-based methods to describe the shape of the autocorrelations and cross-correlation in relevant regions of parameters space. The analytical approach would begin by identifying stable attractors of the deterministic system using classical PDE theory. Following this, we may possibly apply theory of SPDE to describe stationary distributions associated with each attractor. This may lend analytical solutions for the expectation and variance of intraspecific autocorrelations and the interspecific cross-correlation, which are defined in Appendix \ref{corr-defs} below.

\newpage

\appendix

# Definitions of Spatial Autocorrelation and Cross-correlation \label{corr-defs}

## Autocorrelation

In one-dimensional continuous space, the autocorrelation of a function $f$ is defined by

\begin{equation}
  \rho_f(x)=\int_{-\infty}^{+\infty}f(y)f(y-x)dy.
\end{equation}

Sometimes the autocorrelation $\rho_f(x)$ is written as $(f\star f)(x)$. To extend this definition to two-dimensional space, we can calculate a bivariate autocorrelation function of $f$,

\begin{equation}
  \rho_f(x_1,x_2)=\int_{-\infty}^{+\infty}\int_{-\infty}^{+\infty}f(y_1,y_2)f(y_1-x_2,y_2-x_2)dy_1dy_2,
\end{equation}

and then average this quantity across distances $r=\sqrt{x_1^2+x_2^2}$:

\begin{equation}
  \bar\rho_f(r)=\frac{1}{2\pi r}\int_0^{2\pi}\rho_f(r\cos\theta,r\sin\theta)d\theta.
\end{equation}


## Cross-correlation

The cross-correlation of two functions $f,g$ is defined by

\begin{equation}
  \rho_{fg}(x)=\int_{-\infty}^{+\infty}f(y)g(y-x)dy.
\end{equation}

Sometimes this is written as $f\star g$. Just as with the bivariate autocorrelation above, we can extend this definition to two-dimensional space. In particular, the bivariate cross-correlation of two functions $f,g$ can be written

\begin{equation}
  \rho_{fg}(x_1,x_2)=\int_{-\infty}^{+\infty}\int_{-\infty}^{+\infty}f(y_1,y_2)g(y_1-x_2,y_2-x_2)dy_1dy_2.
\end{equation}

We can also reduce this quantity to a function of distance using the average

\begin{equation}
  \bar\rho_{fg}(r)=\frac{1}{2\pi r}\int_0^{2\pi}\rho_{fg}(r\cos\theta,r\sin\theta)d\theta.
\end{equation}

# A Stable Equilibrium of the Deterministic System

To find an equilibrium of the deterministic PDE (\ref{deterministic}) we set the time derivatives of $\bar z_H$ and $\bar z_P$ equal to zero. This leads to following systems of ODE's

\begin{subequations}
  \begin{equation}
    0=G_HA_H(\theta_H-\bar z_H)-G_HB_H(\bar z_P-\bar z_H)+\frac{D_H}{2}\Delta\bar z_H,
  \end{equation}
  \begin{equation}
    0=G_PA_P(\theta_P-\bar z_P)+G_PB_P(\bar z_H-\bar z_P)+\frac{D_P}{2}\Delta\bar z_P.
  \end{equation}
\end{subequations}

Solving this system for the spatial functions $\bar z_H(x_1,x_2)$ and $\bar z_P(x_1,x_2)$ then returns equilibrium solutions to PDE (\ref{deterministic}). However, we can start simple by considering spatially homogeneous solutions. In these cases the spatial derivatives will return zero (in particular, $\Delta\bar z_H=\Delta\bar z_P=0$). Finding these solutions amounts to solve the following system of algebraic equations

\begin{subequations}
  \begin{equation}
    0=G_HA_H(\theta_H-\bar z_H)-G_HB_H(\bar z_P-\bar z_H),
  \end{equation}
  \begin{equation}
    0=G_PA_P(\theta_P-\bar z_P)+G_PB_P(\bar z_H-\bar z_P).
  \end{equation}
\end{subequations}

This linear system is uniquely solved by

\begin{subequations}\label{non-spatial-eq}
  \begin{equation}
    \bar z_P(x_1,x_2)\equiv\frac{(A_H-B_H)A_P\theta_P+B_PA_H\theta_H}{(A_H-B_H)A_P+B_PA_H},
  \end{equation}
  \begin{equation}
    \bar z_H(x_1,x_2)\equiv\frac{(A_P+B_P)A_H\theta_H-B_HA_P\theta_P}{(A_P+B_P)A_H-B_HA_P},
  \end{equation}
\end{subequations}
where the symbol $\equiv$ is used in place of $=$ to emphasize these functions are constant across space.

To understand whether this equilibrium is stable we perform stability analysis on the non-spatial model. Notice that system (\ref{non-spatial}) can be rewritten in matrix notation as $\vec{\bar z}=M\vec{\bar z}+\vec b$ where

\begin{subequations}
  \begin{equation}
    \vec{\bar z}=\left(\begin{matrix}
      \bar z_H \\ \bar z_P
    \end{matrix}\right), \ 
    \vec b =\left(\begin{matrix}
      G_HA_H\theta_H \\ G_PA_P\theta_P
    \end{matrix}\right),
  \end{equation}
  \begin{equation}
    M=\left(\begin{matrix}
      G_H(B_H-A_H) & -G_HB_H \\
      G_PB_P & -G_P(A_P+B_P)
    \end{matrix}\right).
  \end{equation}
\end{subequations}

It turns that if the real parts of the eigenvalues of $M$ are negative then equilibrium (\ref{non-spatial-eq}) is stable. This condition holds in general when $B_H<A_H+(A_P+B_P)G_P/G_H$ and $B_H<A_H(1+B_P/A_P)$. A sufficient condition with clear biological intuition is $B_H<A_H$, which just means the strength of biotic selection on the host is less than the strength of abiotic stabilizing selection.

# Stationary Solutions of SPDE (\ref{spde})

