---
title: "Justification for continuous space model"
header-includes:
  - \usepackage{amsmath}
  - \usepackage{dutchcal}
  - \usepackage{mathrsfs}
  - \usepackage{csquotes}
  - \usepackage{textcomp}
  - \usepackage{cancel}
  - \usepackage[T3,T1]{fontenc}
  - \DeclareSymbolFont{tipa}{T3}{cmr}{m}{n}
  - \DeclareMathAccent{\invbreve}{\mathalpha}{tipa}{16}
output: pdf_document
---

For the sake of space, we omit any attempt to formally derive our continuous space model from biological first principles. Instead we describe a possible approach that can be taken. We make no claim of rigor and no promise of general heuristics that can be employed. Instead, we only provide a schema.

To begin, one may start with a pair of interacting individual-based branching processes where individuals are associated with a trait $z\in\mathbb R$ and a location $\pmb x\in\mathbb R^2$. Assuming semelparous life-cycles, we model mortality and reproduction simultaneously so that individuals replace themselves with a Poisson number of offspring between exponentially distributed intervals. For simplicity, we assume the rate at which these branching events occur is constant. However, the number of offspring is determined by the trait of the parent along with the traits of other individuals the parent interacts with. This is similar to the starting points taken by Week et. al. (2021a) in the derivation of a diffuse-coevolution model and by Week et. al. (2021b) in the derivation of the offset-matching coevolution model, except neither of those models have a spatial component.

To model fitness, we first consider the effects of abiotic selection $\mathcal A_S$ and biotic selection $\mathcal B_S$ separately for host and parasite species ($S=H,P$). Furthermore, we decompose the effects of biotic selection into sources due to intraspecific competition $\mathcal B_S^c$ and interspecific parasitism $\mathcal B_S^p$ so that $\mathcal B_S=\mathcal B_S^c\mathcal B_S^p$. We will assume these effects multiply to produce the net fitness of an individual, $w_S=\mathcal A_S\mathcal B_S$. For either species, the multiplicative component of fitness due to abiotic stabilizing selection for an individual with trait $z$ at any location is

$$\mathcal A_S(z)\propto\exp\left(-\frac{A_S}{2}(\theta_S-z)^2\right).$$

We assume competition occurs locally such that individuals that are geographically closer to each other induce stronger competition on another than individuals that are further apart. This induces a form of local population regulation that prevents run-away population growth. In particular, denoting the distance between two spatial positions $\pmb x$ and $\pmb y$ by $\|\pmb x-\pmb y\|$, $\pmb x_i^S$ the location of the $i$th individual in species $S$, and $n_S$ the number of individuals in species $S$, we model the effect of intraspecific competition on the $j$th individual as

$$\mathcal B_S^c(\pmb x_j,\mathcal N_S)\propto\exp\left(-c_S\sum_{i\neq j}^{n_S}\exp\left(-\frac{\lambda_S}{2}\|\pmb x_j^S-\pmb x_i^S\|^2\right)\right),$$

where $c_S$ denotes the strength of spatial competition, $\lambda_S$ is the rate at which competition decays with distance, and $\mathcal N_S$ denotes the abundance measure for species $S$. In particular, since $\mathcal N_S(U,V)$ returns the number of individuals in species $S$ with trait values in $U\subset\mathbb R$ spatially located in the region $V\subset\mathbb R^2$, $\mathcal N_S$ determines the total abundance and spatial locations of individuals in species $S$.

Host-parasite interactions can be modeled by assuming a probability of infection that is a function of trait values given an encounter has occurred. In particular, assuming a host individual with trait $z^H$ encounters a parasite with trait $z^P$, the probability of infection $\alpha(z^H,z^P)$ can be written as

$$\alpha(z^H,z^P)=\exp\left(-\frac{\gamma}{2}(z^H-z^P)^2\right),$$

where $\gamma\geq0$ determines the sensitivity of this probability to differences in individual trait values. We will always assume weak sensitivity (ie, $\gamma\ll1$) so that $\alpha(z^H,z^P)\approx1-\gamma(z^H-z^P)^2/2$. We model the probability of encounter $\varepsilon$ similarly as a function of the geographical distance between individuals. Denoting $\iota\geq0$ the sensitivity of $\varepsilon$ to distance and $\pmb x^S$ the location of the individual in species $S$, we model the probability of encounter as

$$\varepsilon(\pmb x^H,\pmb x^P)=\exp\left(-\frac{\iota}{2}\|\pmb x^H-\pmb x^P\|^2\right).$$

Unlike the sensitivity of the infection probability, we do not assume $\iota\ll1$ so that encounters may strongly depend on distance. Then, assuming the parasite acquires the benefit $s_P\geq0$ and the host receives the cost $s_H\geq0$, the multiplicative effects of this single interaction on the fitness' of the respective participants are proportional to $\exp(s_P\alpha(z^H,z^P)\varepsilon(\pmb x^H,\pmb x^P))$ and $\exp(-s_H\alpha(z^H,z^P)\varepsilon(\pmb x^P,\pmb x^P))$. Then, assuming every parasite could potentially infect every host, the components of biotic selection due to interspecific interactions for each species can be written

$$\mathcal B_H^p(z^H_j,\pmb x^H_j,\mathcal N_P)\propto\exp\left(-s_H\sum_{i=1}^{n_P}\alpha(z^H_j,z^P_i)\varepsilon(\pmb x_j^H,\pmb x_i^P)\right),$$

$$\mathcal B_P^p(z^P_j,\pmb x^P_j,\mathcal N_H)\propto\exp\left(s_P\sum_{i=1}^{n_H}\alpha(z^H_i,z^P_j)\varepsilon(\pmb x_i^H,\pmb x_j^P)\right).$$

To model mutation and spatial movement, we assume offspring trait values are normally distributed around their parental value (technically, this is done with breeding values, see Week et. al. (2021a)) and offspring locations are bivariate normal around their parental locations with no correlations between the displacements in the two spatial dimensions (ie, dispersal is isotropic).

To take a diffusion limit of this individual-base process, we follow Week et. al. (2021a) so that the rate of branching goes to infinity, the number of initial individuals in each species goes to infinity, the effects of mutation and distances of dispersal go to zero and fitness for each individual goes to unity. We also rescale the probability of parasite encounter so that it converges to a delta function. This means parasitism can only occur locally in the diffusion limit. All of these limits occur simultaneously and at specific rates to ensure the rescaled individual-based processes $\mathcal N_H^{(k)},\mathcal N_P^{(k)}$ converge to well-defined population-level processes $\mathscr N^H,\mathscr N^P$, where $\mathcal N_S^{(k)}$ denotes the $k$th stage of rescaling. In this diffusion limit the growth rates associated with trait value $z$ at location $\pmb x$ can be obtained for each species as

$$m_H(z,\pmb x,\mathscr N^H,\mathscr N^P)=\lim_{k\to\infty}k\left(w^{1/k}_H(z,\pmb x,\mathcal N_H^{(k)},\mathcal N_P^{(k)})-1\right),$$

$$m_P(z,\pmb x,\mathscr N^P,\mathscr N^H)=\lim_{k\to\infty}k\left(w^{1/k}_P(z,\pmb x,\mathcal N_P^{(k)},\mathcal N_H^{(k)})-1\right),$$

where $w_S^{1/k}$ is the fitness function for species $S$ raised to the power of $1/k$. For the host this yields

$$m_H(z,\pmb x,\mathscr N_H,\mathscr N_P)=r_H-\frac{A_H}{2}(\theta_H-z)^2-c_H\int_{\mathbb R^2}K_H(\pmb x,\pmb y)\mathscr N_H(\mathbb R,d\pmb y)-s_H\int_{\mathbb R^2}\int_{\mathbb R}\alpha(z,\zeta)\mathscr N_P(d\zeta,d\pmb x),$$

where $r_H$ is some real number (the intrinsic growth rate) and we set $K_S(\pmb x,\pmb y)=\exp\left(-\frac{\lambda_S}{2}\|\pmb x-\pmb y\|^2\right)$. A similar expression for the parasite is also obtained. We now make the approximation that competition is sufficiently weak and the intrinsic growth rate is sufficiently positive so that local density of abundance is approximately constant in time and space for each species. This implies the population growth rates $m_H,m_P$ are near zero. With this approximation we write $N_S$ as the abundance density for species $S$ so that $\mathscr N_S(\mathbb R,U)=|U|N_S$ for $U\subset\mathbb R^2$ where $|U|$ is the area of $U$. In this case we have

$$\int_{\mathbb R^2}K_S(\pmb x,\pmb y)\mathscr N^S(\mathbb R,d\pmb y)=N_S\frac{2\pi}{\lambda_S}.$$

Using our assumption that $\gamma\ll1$, the biotic and abiotic components cumulatively contribute quadratic selection. Hence, given that stabilizing abiotic selection is sufficiently strong relative to disruptive biotic selection on the host, trait distributions at any location will be approximately normal with mean and variance $\bar z_S(\pmb x),v_S(\pmb x)$ for species $S$ at location $\pmb x$. In particular, this implies

$$\int_{\mathbb R^2}\int_{\mathbb R}\alpha(z,\zeta)\mathscr N^P(d\zeta,d\pmb x)=N_S\left(1-\frac{\gamma}{2}(z-\bar z_P(\pmb x))^2+v_P(\pmb x)\right).$$

Furthermore, since selection is quadratic and abundance is constant, selection and drift decay phenotypic variance at a constant rate. From our assumption of Gaussian mutations, phenotypic variance also has a constant rate of input. Hence, we can expect phenotypic variance for each species to fluctuate stochastically around an equilibrium that is constant in space and time. We thus further approximate by setting the phenotypic variances equal to those constant equilibria. We can therefore approximate the growth rates for each species as

$$m_H(z,\pmb x)\approx R_H-\frac{A_H}{2}(\theta_H-z)^2+\frac{B_H}{2}(z-\bar z_P)^2,$$

$$m_P(z,\pmb x)\approx R_P-\frac{A_P}{2}(\theta_P-z)^2-\frac{B_P}{2}(z-\bar z_P)^2,$$

where $R_H,R_P>0$, $B_P=s_PN_H\gamma$, $B_H=s_HN_P\gamma$ and we have dropped the dependencies on $\mathscr N^H,\mathscr N^P$ for brevity.

To obtain the evolutionary dynamics from these fitness functions, we consider a characterization of the population-level processes $\mathscr N_t^H,\mathscr N_t^P$ as random functions of time. To keep this part of our description as minimal on technical details as possible, we state many propositions without justification. For functions $f(z,\pmb x)$ that decay rapidly to zero as $\|\pmb x\|\to\infty$ and are twice differentiable with respect to space we write

$$\langle\mathscr N_t^S,f\rangle=\int_{\mathbb R^2}\int_{\mathbb R}f(z,\pmb x)\mathscr N^S_t(dz,d\pmb x).$$

The characterization we make use of states that for each $f(z,\pmb x)$ that is twice differentiable and rapidly decreasing in $\pmb x$,

$$M_t(f)=\langle\mathscr N_t^S,f\rangle-\langle\mathscr N_0^S,f\rangle-\int_0^t\left\langle\mathscr N_s^S,\left(m_S+\tfrac{\sigma_S^2}{2}\Delta\right)f\right\rangle ds$$

is a martingale with so-called increasing process $\int_0^t\langle\mathscr N^S_t,f^2\rangle ds$ (Meleard & Roelly). Martingales are stochastic processes that have expectation zero for each $t\geq0$ and their increasing processes inform us about their variance around that expectation. Formally, there should be an additional operator to account for mutation, but since we have reasoned phenotypic variance will be constant this detail is unnecessary for our purposes. However, in order for this approach to work, we do need to take back our assumption of constant population size. Hence, we assume the existence of a spatial abundance density so that $\int_{\mathbb R}\mathscr N_t^S(dz,d\pmb x)=N_S(\pmb x,t)dzd\pmb x$ allow the spatial abundance density $N_S(\pmb x,t)$ to evolve in time and space, but assume it doesn't evolve too much so our approximated growth rates hold. Setting $f(z,\pmb x)=g(\pmb x)$ for a rapidly decaying function $g$, we have

$$\langle\mathscr N_t^S,f\rangle=\int_{\mathbb R^2}N_S(\pmb x,t)g(\pmb x)d\pmb x,$$

and hence the above martingale becomes

$$M_t(g)=\int_{\mathbb R^2}N_S(\pmb x,t)g(\pmb x)d\pmb x-\int_{\mathbb R^2}N_S(\pmb x,0)g(\pmb x)d\pmb x-\int_0^t\int_{\mathbb R^2}N_S(\pmb x,t)\left(\bar m_S(\pmb x,s)g(\pmb x)+\tfrac{\sigma_S^2}{2}\Delta g(\pmb x)\right)d\pmb xds$$

where $\bar m_S(\pmb x,t)d\pmb x=\int_{\mathbb R}m_S(z,\pmb x)\mathscr N^S_t(dz,d\pmb x)/N_S(t)$ and the increasing process becomes $\int_0^tN_S(s)ds$. Similar to how the fundamental theorem of calculus states that the integral equation $F(t)-F(0)-\int_0^tf(s)ds=0$ corresponds to a deterministic differential equation $\dot F=f$, the above characterization suggests the process $N_S(\pmb x,t)$ can be described by some sort of stochastic differential equation. In fact, our characterization for the evolution of $N_S(\pmb x,t)$ coincides with the notion of a weak solution to the following stochastic partial differential equation

$$\dot N_S=\bar m_SN_S+\tfrac{\sigma_S^2}{2}\Delta N_S+\sqrt{N_s}\dot W_{N_S},$$

where $\dot W_{N_S}$ is a space-time white noise process. Similarly, we can consider the martingale for $f(z,\pmb x)=zg(\pmb x)$ 

$$M_t(zg)=\int_{\mathbb R^2}N_S(\pmb x,t)\bar z(\pmb x,t)g(\pmb x)d\pmb x-\int_{\mathbb R^2}N_S(\pmb x,0)\bar z(\pmb x,0)g(\pmb x)d\pmb x$$

$$-\int_0^t\int_{\mathbb R^2}N_S(\pmb x,s)\left(\overline{m z}_S(\pmb x,s)g(\pmb x)+\bar z(\pmb x,s)\tfrac{\sigma_S^2}{2}\Delta g(\pmb x)\right)d\pmb xds$$

where $\overline{mz}_S(\pmb x,t)d\pmb x=\int_{\mathbb R}m_S(z,\pmb x)z\mathscr N_t^S(dz,d\pmb x)/N_S(\pmb x,t)$. For rapidly decaying $g$, $\int_{\mathbb R^2}N_S(\pmb x,t)g(\pmb x)d\pmb x$ and $\int_{\mathbb R^2}N_S(\pmb x,t)\bar z_S(\pmb x)g(\pmb x)d\pmb x$ are univariate diffusion processes with noise determined by the increasing processes of $M_t(g)$ and $M_t(zg)$ respectively. Using this, we can apply Ito's quotient rule to compute a stochastic differential equation for $\int_{\mathbb R^2}N_S(\pmb x,t)\bar z_S(\pmb x)g(\pmb x)d\pmb x/\int_{\mathbb R^2}N_S(\pmb x,t)g(\pmb x)d\pmb x$ (taking into account the martingales $M_t(g),M_t(zg)$ are correlated). Then, after some calculations, making some rearrangements, and invoking spatiotemporal constancy of abundance, we find

$$\int_{\mathbb R^2}\bar z_S(\pmb x,t)g(\pmb x)d\pmb x-\int_{\mathbb R^2}\bar z_S(\pmb x,0)g(\pmb x)d\pmb x-\int_0^t\int_{\mathbb R^2}\bar z_S(\pmb x,s)\left(\mathrm{Cov}_{s,\pmb x}(m_S,z)+\tfrac{\sigma^2_S}{2}\Delta\right)g(\pmb x)ds$$

is a martingale with increasing process $v_S\int_0^t\int_{\mathbb R^2}g^2(\pmb x)d\pmb xds/N_S$ where 

$$\mathrm{Cov}_{t,\pmb x}(m_S,z)d\pmb x=\frac{1}{N_S}\int_{\mathbb R}(m(z,\pmb x)-\bar m_S(\pmb x,t))(z-\bar z_S(\pmb x,t))\mathscr N_t^S(dz,d\pmb x).$$

In particular, this coincides with the definition of the weak solution to the stochastic partial differential equation

$$\dot{\bar z}_S=\mathrm{Cov}(m_S,z)+\tfrac{\sigma^2_S}{2}\Delta\bar z_S+\sqrt{\tfrac{v_S}{N_S}}\dot W_S.$$

To finally obtain our continuous space model, rework all the above in terms of breeding values so that the phenotypic variance $v_S$ is replaced with the additive genetic variance $G_S$ (see Week et. al. 2021a) and then use the fact that when traits are normally distributed at each location and $m_S$ does not depend on $\bar z_S(\pmb x,t)$, $\mathrm{Cov}_{t,\pmb x}(m_S,z)=G_S\tfrac{\partial}{\partial\bar z(\pmb x,t)}\bar m_S(\pmb x,t)$.