---
title: "host-parasite coevolution summary"
output:
  rmdformats::downcute:
    self_contained: true
    highlight: tango
    downcute_theme: "chaos"
    default_style: "light"
editor_options: 
  chunk_output_type: console
---

## a few stats

```{r echo=F, message=FALSE, warning=FALSE,results='asis'}
require(ggplot2)
# require(ggdark)

# pool all ild scores together in matrix
# grab indices for top 99th percentile
# compute the fraction of ild scores in top 99th percentile
# that correspond to causal pairs
# that correspond to one causal locus and one neutral locus

hsnps = as.matrix(read.csv("~/gsccs-data/h-csl-snps.csv",header=F)+1)
psnps = as.matrix(read.csv("~/gsccs-data/p-csl-snps.csv",header=F)+1)

ild = as.matrix(read.csv("~/gsccs-data/ild-cov.csv", header=F))
qtl = quantile(ild,0.99)
topinds = which(ild>qtl, arr.ind = T)

cslprs = topinds[,1] <= length(hsnps) & topinds[,2] <= length(psnps)
cslsgl = (topinds[,1] <= length(hsnps) & !(topinds[,2] <= length(psnps))) | 
  (!(topinds[,1] <= length(hsnps)) & topinds[,2] <= length(psnps))

topttl = length(topinds[,1])
prfrac = sum(cslprs)/topttl
sgfrac = sum(cslsgl)/topttl
cbfrac = prfrac+sgfrac

hprcpt = unique(topinds[cslprs,1])
pprcpt = unique(topinds[cslprs,2])

hcslfrac = length(hprcpt)/length(hsnps)
pcslfrac = length(pprcpt)/length(psnps)

hsgcpt = unique(topinds[cslprs|cslsgl,1])
psgcpt = unique(topinds[cslprs|cslsgl,2])

hsglfrac = length(hsgcpt)/length(hsnps)
psglfrac = length(psgcpt)/length(psnps)

# \/ perhaps do this in python using genotype arrays \/
# for each spp, identify set of causal loci that explain
# 95% of phenotypic variation in the population
# refer to these as "truly causal loci"
# then, compute fraction of these causal loci that occur in
# the 99th percentile of ild scores for
# just the causal pairs
# just the causal "singletons" (ie, one causal one neutral)

descrs = c("Number ild pairs occuring in top 99th percentile",
           "Number host causal loci",
           "Number para causal loci")
vals = c(topttl,length(hsnps),length(psnps))
statdt = cbind(descrs,formatC(as.numeric(vals))) #, digits = 1, format = "e", drop0trailing = FALSE))
statdf = data.frame(statdt)
colnames(statdf) = c("Description","Value")
knitr::kable(statdf)

```

## performance measures

```{r echo=F, message=FALSE, warning=FALSE,results='asis'}
# make table of performance measures
descrs = c("Fraction of top 99th perc corresponding to causal pairs",
           "Fraction of top 99th perc corresponding to one causal locus",
           "Combined fraction corresponding to one or two causal loci",
           "Fraction host loci corresponding to causal pair in 99th per",
           "Fraction para loci corresponding to causal pair in 99th per",
           "Fraction host loci corresponding appearing in 99th per",
           "Fraction para loci corresponding appearing in 99th per")
vals = c(prfrac,sgfrac,cbfrac,hcslfrac,pcslfrac,hsglfrac,psglfrac)
pfmsrdt = cbind(descrs,formatC(as.numeric(vals))) #, digits = 1, format = "e", drop0trailing = FALSE))
pfmsr = data.frame(pfmsrdt)
colnames(pfmsr) = c("Description","Value")
knitr::kable(pfmsr)
```

## ild score vs trait variance score

```{r echo=F, message=FALSE, warning=FALSE,results='asis'}
colors <- c("Parasite" = "purple", "Host" = "orange")

# insert plots of ild x effect size for both spp
# where each effect size is associated with all ild at that locus
# check if effect size correlates with max(ild)

# might want to multiply effect size by genetic variance

# for a trait Z=a*I, I~Bern(p) and a in R, Var(Z)=a^2*p(1-p)
# so, for L unlinked loci, Var(Z)=sum_i(a[i]^2*p[i]*(1-p[i]))
# and the prop of var explained by locus l is
# a[l]^2*p[l]*(1-p[l])/Var(Z)
# ignored not only ld, but also homozygosity

hes = as.matrix(read.csv("~/gsccs-data/h-effect-sizes.csv", header=F))
pes = as.matrix(read.csv("~/gsccs-data/p-effect-sizes.csv", header=F))
hfq = as.matrix(read.csv("~/gsccs-data/hfrq-csl-gbl.csv", header = F))
pfq = as.matrix(read.csv("~/gsccs-data/pfrq-csl-gbl.csv", header = F))

hvrsk = hes^2*hfq*(1-hfq)
pvrsk = pes^2*pfq*(1-pfq)

hmaxild = rep(0,length(hes))
for(i in 1:length(hes)){
  hmaxild[i] = max(abs(ild[i,]))
}
pmaxild = rep(0,length(pes))
for(i in 1:length(pes)){
  pmaxild[i] = max(abs(ild[i,]))
}

skild = data.frame(sk=abs(c(hvrsk,pvrsk)), 
           ild=c(hmaxild,pmaxild), 
           spp=c(rep("Host",length(hes)),rep("Parasite",length(pes))))

ggplot(skild) + 
  geom_point(aes(x=sk,y=ild, color=spp)) +
  labs(x = "(Sqr Effect Size)*(Genetic Var)",        
       y = "max(ILD)",        
       color = "Legend") +
  scale_color_manual(values = colors) +
  theme_minimal()

# ntl_ild_cor = read.csv("~/gsccs-data/ntl-ild-cor-flat.csv", header = F)
# ntl_ild_cov = read.csv("~/gsccs-data/ntl-ild-cov-flat.csv", header = F)
# csl_ild_cor = read.csv("~/gsccs-data/csl-ild-cor-flat.csv", header = F)
# csl_ild_cov = read.csv("~/gsccs-data/csl-ild-cov-flat.csv", header = F)
# 
# kprs = list(ntlcor=1,ntlcov=2,cslcor=3,cslcov=4)
# dfs = list(ntlcor=ntl_ild_cor,ntlcov=ntl_ild_cov,cslcor=csl_ild_cor,cslcov=csl_ild_cov)
# 
# for(i in 1:2){
#   dfs[[i]]$V1 = abs(dfs[[i]]$V1)
#   qtl = quantile(dfs[[i]]$V1,0.99)
#   kprs[[i]] = which(dfs[[i]]$V1>qtl)
# }
# for(i in 3:4){
#   dfs[[i]]$V1 = abs(dfs[[i]]$V1)
#   qtl = quantile(dfs[[i-2]]$V1,0.99)
#   kprs[[i]] = which(dfs[[i]]$V1>qtl)
# }
# 
# lumpnms = c(rep("ntl",length(kprs$ntlcor)),rep("csl",length(kprs$cslcor)))
# lumpcrs = c(dfs$ntlcor$V1[kprs$ntlcor],dfs$cslcor$V1[kprs$cslcor])
# cor_df = data.frame(lumpcrs,lumpnms)
# colnames(cor_df) = c("ild","set")
# 
# lumpnms = c(rep("ntl",length(kprs$ntlcov)),rep("csl",length(kprs$cslcov)))
# lumpcvs = c(dfs$ntlcov$V1[kprs$ntlcov],dfs$cslcov$V1[kprs$cslcov])
# cov_df = data.frame(lumpcvs,lumpnms)
# colnames(cov_df) = c("ild","set")
# 
# ggplot(cor_df) +
#   geom_histogram(aes(x=ild,y=..density..,fill=set),
#                  bins=50,alpha=0.25,position = "identity") +
#   xlab("99th Perc Spatial Correlations") +
#   ylab("Density") +
#   theme_minimal()
# 
# ggplot(cov_df) +
#   geom_histogram(aes(x=ild,y=..density..,fill=set),
#                  bins=50,alpha=0.25,position = "identity") +
#   xlab("99th Perc Spatial Covariances") +
#   ylab("Density") +
#   theme_minimal()
```

## time-series

```{r echo=F, message=FALSE, warning=FALSE,results='asis'}
params = read.csv("~/gsccs-data/params.csv")
tsdf = read.csv("~/gsccs-data/time-series.csv")

ggplot(tsdf) + 
  geom_line(aes(x=t,y=Nh,color="Host")) +
  geom_line(aes(x=t,y=Np,color="Parasite")) +
  labs(x = "Time",        
       y = "Global Census Size",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=zh,color="Host")) +
  geom_line(aes(x=t,y=zp,color="Parasite")) +
  labs(x = "Time",        
       y = "Global Trait Means",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=vh,color="Host")) +
  geom_line(aes(x=t,y=vp,color="Parasite")) +
  labs(x = "Time",        
       y = "Global Trait Stddevs",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

frqs = read.csv("~/gsccs-data/mut-freqs.csv")

frqs$frq[frqs$frq==0] = NA

hfq.df = subset(frqs,spp==1)
pfq.df = subset(frqs,spp==2)

ggplot(hfq.df,aes(x=t,y=frq)) + 
  geom_line(aes(color=as.character(id)),alpha=0.5,lwd=.2) + 
  xlab("Time") +
  ylab("Host Mutation Freqs") +
  theme_minimal() +
  theme(legend.position="none")

ggplot(pfq.df,aes(x=t,y=frq)) + 
  geom_line(aes(color=as.character(id)),alpha=0.5,lwd=0.2) + 
  xlab("Time") +
  ylab("Para Mutation Freqs") +
  theme_minimal() +
  theme(legend.position="none")

ggplot(tsdf) + 
  geom_line(aes(x=t,y=muh,color="Host")) +
  geom_line(aes(x=t,y=mup,color="Parasite")) +
  labs(x = "Time",
       y = "Num Polymorphic Loci",
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=pntcorr)) +
  labs(x = "Time",        
       y = "Spatial Correlation of Traits",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  ylim(c(-1,1)) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=abar)) +
  labs(x = "Time",
       y = "Average Infection Probability",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

# ggplot(tsdf) + 
#   geom_line(aes(x=t,y=vara)) +
#   labs(x = "Time",        
#        y = "Variance of Infection Probability",
#        color = "Legend") +   
#   scale_color_manual(values = colors) +
#   theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=hselresp)) +
  labs(x = "Time",        
       y = "Host Response to Biotic Selection",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=pselresp)) +
  labs(x = "Time",        
       y = "Parasite Response to Biotic Selection",
       color = "Legend") +   
  scale_color_manual(values = colors) +
  theme_minimal()

ggplot(tsdf) + 
  geom_line(aes(x=t,y=(1-pr_unparasitized),color="Host")) +
  geom_line(aes(x=t,y=(1-pr_unhosted),color="Parasite")) +
  labs(x = "Time",        
       y = "Proportion Interaction Attempted",        
       color = "Legend") +   
  scale_color_manual(values = colors) +
  ylim(c(0,1)) +
  theme_minimal()
```

## parameter values

```{r echo=F, message=FALSE, warning=FALSE,results='asis'}
descrs = c("host mutation rate","parasite mutation rate","host mutation effect size","parasite mutation effect size",
           "host dispersal distance","parasite dispersal distance","host-parasite interaction dist","host competition",
           "parasite competition","host competition dist","parasite competition dist","host base fitness","parasite base fitness",
           "host biotic selection","parasite biotic selection","infection probability sensitivity","host initial density",
           "parasite initial density","temporal resolution of time-series")
txtdat = cbind(colnames(params),descrs,formatC(as.numeric(params), digits = 1, format = "e", drop0trailing = FALSE))
txtdf = data.frame(txtdat)
colnames(txtdf) = c("Param","Description","Value")

knitr::kable(txtdf)
```
